version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=TGV MAX Checker
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      # Web scraping configuration
      - NEXT_PUBLIC_USE_MOCK_DATA=false
      - SNCF_CONNECT_HEADLESS=true
      - SNCF_CONNECT_TIMEOUT=30000
      - CACHE_TTL=300
      # Puppeteer configuration
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s