version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_NAME=TGV MAX Checker (Dev)
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - WATCHPACK_POLLING=true  # Enable hot reload in Docker
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev